name: Build project on Linux

on:
  push:
    branches:
      - Linux-CI
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  buildNativeDir: '${{ github.workspace }}/buildNative/'
jobs:
  init: 
    name: Init build
    runs-on: ubuntu-latest
    steps:
      - name: Install apt packages
        run: sudo apt -y install gfortran libx11-dev mesa-common-dev libxi-dev make swig autoconf autoconf-archive libtool texinfo curl autopoint libgl1-mesa-dev libglu1-mesa-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxkbcommon-dev libxkbcommon-x11-dev libfontconfig1-dev libfreetype6-dev '^libxcb.*-dev' python gperf
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: lukka/get-cmake@latest
      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v7
        with:
          setupOnly: true
          appendedCacheKey: ${{ hashFiles( '${{ github.workspace }}/Plugins/vcpkg.json' ) }}
          vcpkgGitCommitId: 1257354a3ab0bebd8abe95281ca561537853578c
          vcpkgTriplet: ${{ matrix.triplet }}
          additionalCachedPaths: ${{ env.buildNativeDir }}/vcpkg_installed
      - name: Install vcpkg packages 
        run: |
          $VCPKG_ROOT/vcpkg install fastrtps openmvs
          shell: bash
      - name: Upload logs if failed
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: vcspkg_logs
          path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
 
