name: Build project

on:
  pull_request: { }
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:
  build:
    name: Build for StandaloneWindows64
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Build unity player
        run: .\.github\build.bat ${{ secrets.UNITY_SERIAL }} ${{ secrets.UNITY_USERNAME }} ${{ secrets.UNITY_PASSWORD }}
  runTest:
    name: Run tests
    runs-on: self-hosted
    needs: build
    steps:
      - name: Report unity editor tests
        uses: zyborg/dotnet-tests-report@v1
        with:
          test_results_path: .\tests.xml
          set_check_status_from_test_outcome: true
          report_name: unity_editor_tests
          report_title: Unity editor tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run protobuf plugin unit tests
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: plugins/Protobuf.Tests.Internal
          set_check_status_from_test_outcome: true
          report_name: protobuf_unit_tests
          report_title: Protobuf unit tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run ROS plugin unit tests
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: plugins/ROS.Tests
          set_check_status_from_test_outcome: true
          report_name: ros_unit_tests
          report_title: ROS unit tests
          github_token: ${{ secrets.GITHUB_TOKEN }}