name: Build project on Linux

on:
  push:
    branches:
      - Linux-CI
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  buildNativeDir: '${{ github.workspace }}/buildNative/'
jobs:
  init: 
    name: Init build
    runs-on: ubuntu-latest
    steps:
      - name: Install apt packages
        run: sudo apt-get install gfortran libx11-dev mesa-common-dev libxi-dev make swig
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: lukka/get-cmake@latest
      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v7
        with:
          setupOnly: true
          appendedCacheKey: ${{ hashFiles( '${{ github.workspace }}/Plugins/vcpkg.json' ) }}
          vcpkgGitCommitId: 1257354a3ab0bebd8abe95281ca561537853578c
          vcpkgTriplet: ${{ matrix.triplet }}
          additionalCachedPaths: ${{ env.buildNativeDir }}/vcpkg_installed
      - name: Install vcpkg packages 
        run: |
          $VCPKG_ROOT/vcpkg install fastrtps oppenmvs
          shell: bash
 