name: Build project on Linux (fork)

on:
  push:
    branches:
      - Linux-CI
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  buildNativeDir: '${{ github.workspace }}/buildNative/'
jobs:
  init: 
    name: Init build
    runs-on: ubuntu-latest
    steps:
      - name: Install apt packages
        run: sudo apt -y install make swig curl python
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: lukka/get-cmake@latest
      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v7
        with:
          setupOnly: true
          appendedCacheKey: ${{ hashFiles( '${{ github.workspace }}/Plugins/vcpkg.json' ) }}
          vcpkgGitCommitId: 1257354a3ab0bebd8abe95281ca561537853578c
          vcpkgTriplet: ${{ matrix.triplet }}
          additionalCachedPaths: ${{ env.buildNativeDir }}/vcpkg_installed
      - name: Install vcpkg packages 
        run: $VCPKG_ROOT/vcpkg install fastrtps opencv
      - name: Upload logs if failed
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: vcspkg_logs
          path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
 
