name: Build project

on:
  pull_request: { }
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:
  buildForSomePlatforms:
    name: Build for StandaloneWindows64
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Build unity player
        run: .\.github\build.bat ${{ secrets.UNITY_SERIAL }} ${{ secrets.UNITY_USERNAME }} ${{ secrets.UNITY_PASSWORD }}
      - uses: MirrorNG/nunit-reporter@v1.0.9
          if: always()
          with:
            path: tests.xml
            access-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run plugins tests
        run: |
          cd ./plugins
          dotnet test --configuration Release
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
