# This is a basic workflow to help you get started with Actions

name: Build project

# Controls when the action will run. 
on:
  pull_request: {}
  push: {}
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:
  buildForSomePlatforms:
    name: Build for StandaloneWindows64  on version 2020.2.4f1
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build unity player
        run: .\.github\build.bat ${{ secrets.UNITY_SERIAL }} ${{ secrets.UNITY_USERNAME }} ${{ secrets.UNITY_PASSWORD }}
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
